<div>
    <form action="objects/list" name="ajaxForm" id="ajaxForm">
        <div class="fl">
            <select name="objectTypeId" id="objectTypeId">
                <option value="">--Select--</option>
                <?php
                    foreach($this->items as $item){
                ?>
                    <option value="<?php echo $item->getId() ?>"><?php echo $this->translate($item->getName()); ?></option>
                <?php
                    }
                ?>
            </select>
        </div>
        <div class="fl">
            <input type="button" value="filter" onclick="Form.submit('ajaxForm');return false;">
        </div>
    </form>
    <a href="objects/edit">add</a>
    <table class="mt20">
    	<tbody>
    		<tr class="head">
                <td>
                </td>
            </tr>
    		<tr class='panel'>
    			<td><?php echo $this->action('list', 'objects');?></td>
    		</tr>
    	</tbody>
    </table>
</div>