<?php 
    $this->setPageTitle('objets'); 
    $formatting = $this->getHelper('DataFormatting');
?>
<script>
$(function(){
    Grid.init('club/list');
    callback = function(){
        var options = { 
                dataType:'json',
                success: function(result) { 
                	if (Notify.show(result) == true){                     	
                        //hiding popup box
                        Popup.hide();
                        //show loader
                        Mask.showLoader();                                                        
                        //reload page
                        Url.load('club');                    
                    }
                }
            };             
        $('#ajaxFormDeleteClub').ajaxSubmit(options);               
    }; 
    init = {buttons:[{name:'<?php echo $this->translate('yes') ?>',callback: callback}]};
    clubDelete = new Popup(init);
    removeForm.init('club/delete','deleteFormDiv');
    $(document).ready(function(){
        $(".selectChange select").on("change",function(){
            Form.changeAction('siteFilter','inventory/siteslist');
            Filter.submit('siteFilter','sitelist');
        });
    });
});

</script>
<div id="deleteFormDiv">

</div>
<div class="page_title">
    <div><?php echo $this->translate('clubs');?></div>
</div>

<div class="table_wrapper ml20 mt20">

    <table class="mt20">
    	<tbody>
    		<tr class="head">
                <td>
                    <table class="tlf">
                        <colgroup>
                            <col class="w48">
                            <col class="w75">
                            <col class="">
                        </colgroup>
                        <thead class="zebra header_zebra">
                            <tr>
                                <th class="middle left br0" title=""><span></span></th>
                                <th class="middle left header pl32" id="id" onclick="Grid.sort('id')" title="<?php echo $val=$formatting->toUppercase($this->translate('id')); ?>"><span><?php echo $val; ?></span></th>
                                <th class="middle left header bl0" id="name" onclick="Grid.sort('name')" title="<?php echo $val=$formatting->toUppercase($this->translate(array('club','name'))); ?>"><span><?php echo $val; ?></span></th>
                            </tr>
                        </thead>
                    </table>
                </td>
            </tr>
    		<tr class='panel'>
    			<td><?php echo $this->action('list', 'objects');?></td>
    		</tr>
    	</tbody>
    </table>
    
</div>


