<script>
	selected = '';
	$(function(){
		/*$('.menu').click(function(){
			$('.forFInd').hide(500);
		});
		$('.objectsTypes').click(function(){
			if(selected != 'objectsTypes'){
				selected = 'objectsTypes';
				$('.forFInd').hide(500);
				$('.objectsTypesLink').show(500);
			}
		});
		$('.publisherListLink').click(function(){
			if(selected != 'publisherListLink'){
				selected = 'publisherListLink';
				$('.forFInd').hide(500);
				$('.publisherLinkDiv').show(500);
			}
		});*/
		/*$('.shopListLink').click(function(){
			if(selected != 'shopListLink'){
				selected = 'shopListLink';
				$('.forFInd').hide(500);
				$('.shopLinkDiv').show(500);
			}
		});*/
		$('#startBar>div').draggable();
        $('#startBar>div').draggable({ containment: "body", scroll: false });
	});
</script>
<div id="startBar">
	<div class="ml5 w100">
		<a href="objecttype" data-href="objecttype" onclick="windowObject.create(this)" class="link"><img src="images/mapmenu/Folder.png" style="width:50px;"><br><?php echo $this->translate('objecttype')?></a>
	</div>
    <div class="ml5 w100">
		<a href="publisher" data-href="publisher"  onclick="windowObject.create(this)" class="link"><img src="images/mapmenu/Folder.png" style="width:50px;"><br><?php echo $this->translate('publisher')?></a>
	</div>
	<div class="ml5 w100">
		<a href="shoplist" ata-href="shoplist"  onclick="windowObject.create(this)" class="link"><img src="images/mapmenu/Folder.png" style="width:50px;"><br><?php echo $this->translate('shoplist')?></a>
	</div>
</div>