<script>
	selected = '';
	$(function(){
		/*$('.menu').click(function(){
			$('.forFInd').hide(500);
		});
		$('.objectsTypes').click(function(){
			if(selected != 'objectsTypes'){
				selected = 'objectsTypes';
				$('.forFInd').hide(500);
				$('.objectsTypesLink').show(500);
			}
		});
		$('.publisherListLink').click(function(){
			if(selected != 'publisherListLink'){
				selected = 'publisherListLink';
				$('.forFInd').hide(500);
				$('.publisherLinkDiv').show(500);
			}
		});*/
		/*$('.shopListLink').click(function(){
			if(selected != 'shopListLink'){
				selected = 'shopListLink';
				$('.forFInd').hide(500);
				$('.shopLinkDiv').show(500);
			}
		});*/
		$('#startBar>div').draggable();
        $('#startBar>div').draggable({ containment: "body", scroll: false });
	});
</script>
<div id="startBar">
	<div class="ml5 folderIcon newWindow">
		<a data-href="objecttype" class="link"><img src="images/mapmenu/Folder.png"><div><?php echo $this->translate('objecttype')?></div></a>
	</div>
    <div class="ml5 folderIcon  newWindow">
		<a data-href="publisher"class="link"><img src="images/mapmenu/Folder.png"><div><?php echo $this->translate('publisher')?></div></a>
	</div>
	<div class="ml5 folderIcon  newWindow">
		<a data-href="shoplist" class="link"><img src="images/mapmenu/Folder.png"><div><?php echo $this->translate('shoplist')?></div></a>
	</div>
</div>