<style>
    .menuBarCollumn{
        width:100%;
    }
    .menuBarCollumn>a{
        height:100%;
        width:100%;
        display:block;
        background: rgb(211, 211, 211);
        padding:5%;
    }
    .menuBarCollumn>a:hover{
      background:  rgb(196, 196, 196);
    }
</style>    
<div style="width:100%;">
    <div class="menuBarCollumn startWindow">
        <a class="link" data-href="objects">objects</a>
    </div>
    <div class="menuBarCollumn startWindow">
    <a class="link" data-href="objecttype">object types</a>
    </div>
    <div class="menuBarCollumn startWindow">
    <a class="link" data-href="publisher">publishers</a>
    </div>
    <div class="menuBarCollumn startWindow">
    <a class="link" data-href="shoplist">shops</a>
    </div>
    <div class="menuBarCollumn startWindow">
    <a class="link" data-href="">programs</a>
    </div>
    <div class="menuBarCollumn startWindow">
        <a class="link" data-href="">search</a>
    </div>
</div>