<style>
    .menuBarCollumn{
        height:40px;
        width:200px;
    }
    .menuBarCollumn>a{
        height:40px;
        width:200px;
        display:block;
        background: rgb(211, 211, 211);
        padding:10px;
    }
    .menuBarCollumn>a:hover{
      background:  rgb(196, 196, 196);
    }
</style>    
<div>
    <div class="menuBarCollumn">
        <a class="link" href="objects">objects</a>
    </div>
    <div class="menuBarCollumn">
    <a class="link" href="objecttype">object types</a>
    </div>
    <div class="menuBarCollumn">
    <a class="link" href="publisher">publishers</a>
    </div>
    <div class="menuBarCollumn">
    <a class="link" href="shoplist">shops</a>
    </div>
    <div class="menuBarCollumn">
    <a class="link" href="">programs</a>
    </div>
    <div class="menuBarCollumn">
        <a class="link" href="">search</a>
    </div>
    <div style="height:50px;">
    </div>
</div>