<form action="auth/login" method="POST" id="loginForm" name="loginForm">
    <div id="loginInfo">  
    <?php
        if($this->name){
            echo '<span class="fl">'.$this->translate('hi').'  '.$this->name.'</span>'; ?>
        <input  class="fl ml5 mt5" type="button" onclick = 'Form.changeAction("loginForm","auth/logout");Filter.submit("loginForm","loginInfo");' class="loginButton" value="<?php echo $this->translate('log.out') ?>">
            
     <?php   }else {
     ?>
                <div  class="fl ml5 mt5">
                    <input type="text" id="username" name="email" placeholder="Username">
                </div>
                <div  class="fl ml5 mt5">    
                    <input type="password" id="password" name="password" placeholder="Password" >
                </div>            
                <input  class="fl ml5 mt5" type="button" onclick = 'Form.changeAction("loginForm","auth/login");Filter.submit("loginForm","loginInfo");'class="loginButton" value="<?php echo $this->translate('log.in') ?>">
           
            <a href="user/edit" class="ml5 mt5">Registration</a>
            <label class="loginError fl">
                <?php 
                if($this->loginfailed) { 
                    echo $this->translate('auth.failed'); 
                } 
                ?>	
            </label>
    <?php
        }
    ?>
    </div>
 </form>
