<!DOCTYPE>
<html>
<head>
    <?php 
        $jsHelper = $this->getHelper('js');
        $jsHelper->urlChecker();
        echo $this->headMeta();        
    ?>
    <title><?php echo $this->translate('project.name')?></title>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <link rel="stylesheet" type="text/css" href="css/style.css" />  
	<link rel="stylesheet" href="css/menu.css" type="text/css" media="screen" />
    <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
    <?php 
    echo $this->headScript()
    ->appendFile('js/jquery-1.8.2.min.js', 'text/javascript')
    ->appendFile('js/jquery-ui-1.10.3.custom.min.js', 'text/javascript')    
    ->appendFile('js/plugins/jquery.tablesorter.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.form.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.pnotify.min.js', 'text/javascript')
    ->appendFile('js/plugins/history.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.mousewheel.js', 'text/javascript')
    ->appendFile('js/plugins/custom.form.elements.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.jqtransform.js', 'text/javascript');        
    ?>
    <?php echo $this->action("index", "Jsmin"); ?>
    </head>
<body id="body" style="overflow:hidden;background-image:url('<?php echo $this->action("islogin", "auth"); ?>');background-size:100% 100%;">
	<div class="content_wrapper">
		<div class="content_container">
			<div class="ml5 mr5">
				<div class="fl r100">
					<?php echo $this->action("menu", "objects"); ?>
				</div>
			</div>
			<div class="fl ml20">
					 
			</div>
		</div>
		<div class="cl"></div>
	</div>
    <div class="page_wrapper" style="opacity: 0.9;">
	
		<div id="startMenuBar" style="position:fixed;bottom:5%;display:none;width:12%;">
			<?php echo $this->action("startmenu", "objects"); ?>
		</div>
        <a class="link fl ml5" style="color:black;margin-right:10%;" id="startMenu"><img src="images/backgrounds/startIco.png" title="start" style="height:100%;"></a>
         <div class="fl mr5 startWindow">
			<a class="link" style="color:black;" data-href="auth/login"><img src="images/backgrounds/myFolder.png" title="my folder" style="height:100%;"></a>
		</div>
	</div>	
</body>
</html>